# Generated by Django 4.0.5 on 2023-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_video_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='storage',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
