# Generated by Django 4.0.5 on 2023-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_alter_video_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='storage',
            field=models.FileField(upload_to='static/media/'),
        ),
    ]
